language: python

matrix:
  include:
    - python: 2.7

# start Virtual X, so default matplotlib backend works
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - pip install --upgrade pip
    - pip install codecov

# Install dependencies
install:
    pip install -r requirements.travis.txt

#Command to run tests
script:
   - nosetests tests -v --with-coverage
